version: '3.8'

services:
  apache-tomcat:
    build: .
    ports:
      - "80:80"
      - "443:443"
    hostname: my.tomcat.local
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true -Xmx128m -Xms64m
      - TOMCAT_USERNAME=tomcatuser
      - TOMCAT_PASSWORD=TOMcat
